In [2]:
import sqlite3
import pandas as pd
import os

db_path = os.path.join("..", "data", "test_data.db")
conn = sqlite3.connect(db_path)


events = pd.read_sql("SELECT * FROM events", conn)
captures = pd.read_sql("SELECT * From captures", conn)

print(events.head())
print(captures.head())

                                     id                         timestamp  \
0  6ce0a518-965b-41a4-bc1d-db8154b6cac2  2026-02-23T07:41:40.689000+00:00
1  922c1878-ddf5-44f6-9027-e1cfca448cb9  2026-02-23T07:41:41.343000+00:00
2  add44cc3-3719-4ae6-8811-a206df9cc9c5  2026-02-23T07:41:45.001000+00:00
3  0b8a616b-ac23-4b24-898f-845bb0f40229  2026-02-23T07:41:47.498000+00:00
4  ddfbbc48-938a-4335-8658-10daee5bf2a7  2026-02-23T07:41:50.007000+00:00

         timezone    app_name  \
0  Africa/Nairobi    flet.exe
1  Africa/Nairobi  chrome.exe
2  Africa/Nairobi    flet.exe
3  Africa/Nairobi    flet.exe
4  Africa/Nairobi    flet.exe

                                        window_title       event url  \
0                                      Mate (0.0.11)      ACTIVE
1  Chipchip staff credentials - Google Sheets - G...  APP_SWITCH
2                                      Mate (0.0.11)       CLICK
3                                      Mate (0.0.11)  APP_SWITCH
4                                      Mate (0.0.11)       CLICK

   is_browser clipboard_content clipboard_action       browser_account  \
0           0              None             None                  None
1           1              None             None  maregebru7@gmail.com
2           0              None             None                  None
3           0              None             None                  None
4           0              None             None                  None

  id_employee source_folder_date
0    EMP-0053              Feb23
1    EMP-0053              Feb23
2    EMP-0053              Feb23
3    EMP-0053              Feb23
4    EMP-0053              Feb23
                                     id                              event_id  \
0  860017fb-b737-4adc-b0a3-7f34133a6ae6  922c1878-ddf5-44f6-9027-e1cfca448cb9
1  f55df29e-8b44-47e0-8d7f-9ba53bc918df  add44cc3-3719-4ae6-8811-a206df9cc9c5
2  8896b1a0-e39b-4ac6-840d-9e7318f7b369  ddfbbc48-938a-4335-8658-10daee5bf2a7
3  7438ed0c-a376-4178-a209-242e073574b0  6b9f8c13-20b4-4907-8a8f-19794f947078
4  7445052d-2b83-44bc-9a80-1cb443e9be8d  b0f1fe7c-8e50-42b4-a394-c6472543ad70

                          timestamp  \
0  2026-02-23T07:41:41.343000+00:00
1  2026-02-23T07:41:45.001000+00:00
2  2026-02-23T07:41:50.007000+00:00
3  2026-02-23T07:41:54.641353+00:00
4  2026-02-23T07:42:55.987333+00:00

                                          image_path id_employee  \
0  https://fra1.digitaloceanspaces.com/mgscreensh...    EMP-0053
1  https://fra1.digitaloceanspaces.com/mgscreensh...    EMP-0053
2  https://fra1.digitaloceanspaces.com/mgscreensh...    EMP-0053
3  https://fra1.digitaloceanspaces.com/mgscreensh...    EMP-0053
4  https://fra1.digitaloceanspaces.com/mgscreensh...    EMP-0053

  source_folder_date department
0              Feb23  Marketing
1              Feb23  Marketing
2              Feb23  Marketing
3              Feb23  Marketing
4              Feb23  Marketing

In [11]:
df = pd.read_sql("""
SELECT *
FROM captures c
JOIN events e
ON c.event_id = e.id
""", conn)

df.head()

,id,event_id,timestamp,image_path,id_employee,source_folder_date,department,id,timestamp,timezone,app_name,window_title,event,url,is_browser,clipboard_content,clipboard_action,browser_account,id_employee,source_folder_date
0,860017fb-b737-4adc-b0a3-7f34133a6ae6,922c1878-ddf5-44f6-9027-e1cfca448cb9,2026-02-23T07:41:41.343000+00:00,https://fra1.digitaloceanspaces.com/mgscreensh...,EMP-0053,Feb23,Marketing,922c1878-ddf5-44f6-9027-e1cfca448cb9,2026-02-23T07:41:41.343000+00:00,Africa/Nairobi,chrome.exe,Chipchip staff credentials - Google Sheets - G...,APP_SWITCH,,1,None,None,maregebru7@gmail.com,EMP-0053,Feb23
1,f55df29e-8b44-47e0-8d7f-9ba53bc918df,add44cc3-3719-4ae6-8811-a206df9cc9c5,2026-02-23T07:41:45.001000+00:00,https://fra1.digitaloceanspaces.com/mgscreensh...,EMP-0053,Feb23,Marketing,add44cc3-3719-4ae6-8811-a206df9cc9c5,2026-02-23T07:41:45.001000+00:00,Africa/Nairobi,flet.exe,Mate (0.0.11),CLICK,,0,None,None,None,EMP-0053,Feb23
2,8896b1a0-e39b-4ac6-840d-9e7318f7b369,ddfbbc48-938a-4335-8658-10daee5bf2a7,2026-02-23T07:41:50.007000+00:00,https://fra1.digitaloceanspaces.com/mgscreensh...,EMP-0053,Feb23,Marketing,ddfbbc48-938a-4335-8658-10daee5bf2a7,2026-02-23T07:41:50.007000+00:00,Africa/Nairobi,flet.exe,Mate (0.0.11),CLICK,,0,None,None,None,EMP-0053,Feb23
3,7438ed0c-a376-4178-a209-242e073574b0,6b9f8c13-20b4-4907-8a8f-19794f947078,2026-02-23T07:41:54.641353+00:00,https://fra1.digitaloceanspaces.com/mgscreensh...,EMP-0053,Feb23,Marketing,6b9f8c13-20b4-4907-8a8f-19794f947078,2026-02-23T07:41:54.641353+00:00,Africa/Nairobi,flet.exe,Mate (0.0.11),Custom_CLICK,,0,None,None,None,EMP-0053,Feb23
4,7445052d-2b83-44bc-9a80-1cb443e9be8d,b0f1fe7c-8e50-42b4-a394-c6472543ad70,2026-02-23T07:42:55.987333+00:00,https://fra1.digitaloceanspaces.com/mgscreensh...,EMP-0053,Feb23,Marketing,b0f1fe7c-8e50-42b4-a394-c6472543ad70,2026-02-23T07:42:55.987333+00:00,Africa/Nairobi,flet.exe,Mate (0.0.11),Custom_CLICK,,0,None,None,None,EMP-0053,Feb23

In [4]:
df["event"].value_counts()

event
Custom_CLICK           10085
APP_SWITCH              1843
CLICK                   1812
TYPE                    1244
MOVE                     253
Custom_COPY_ACTION       212
Custom_SCROLL             92
Custom_PASTE_ACTION       74
COPY_ACTION                7
SCROLL                     4
PASTE_ACTION               3
Custom_CUT_ACTION          1
Name: count, dtype: int64

In [5]:
df["app_name"].value_counts()

app_name
chrome.exe                                                       6740
brave.exe                                                        3620
Telegram.exe                                                     2361
Postman.exe                                                      1051
explorer.exe                                                      547
EXCEL.EXE                                                         505
flet.exe                                                          164
ShellExperienceHost.exe                                           140
msedge.exe                                                         62
unknown                                                            54
Spotify.exe                                                        44
opera.exe                                                          42
Photos.exe                                                         36
mspaint.exe                                                        34
Taskmgr.exe                                                        28
notepad.exe                                                        24
Code.exe                                                           23
qbittorrent.exe                                                    21
LockApp.exe                                                        20
ApplicationFrameHost.exe                                           17
ShellHost.exe                                                      14
timedoctor2.exe                                                    11
Cloudflare WARP.exe                                                 9
SearchApp.exe                                                       9
PickerHost.exe                                                      8
Teams.exe                                                           5
SearchHost.exe                                                      5
OpenWith.exe                                                        5
msiexec.exe                                                         4
SnippingTool.exe                                                    4
wps.exe                                                             4
pycharm64.exe                                                       4
Mate-V11.exe                                                        3
System Idle Process                                                 2
WINWORD.EXE                                                         2
StartMenuExperienceHost.exe                                         2
CodeSetup-stable-072586267e68ece9a47aa43f8c108e0dcbf44622.tmp       2
flux.exe                                                            1
rustrover64.exe                                                     1
cmd.exe                                                             1
jetbrains-toolbox.exe                                               1
Name: count, dtype: int64

In [12]:
query = """
SELECT 
    c.id_employee, 
    c.timestamp, 
    e.app_name, 
    e.window_title, 
    e.event, 
    e.url, 
    c.image_path
FROM captures c
JOIN events e ON c.event_id = e.id
ORDER BY c.id_employee, c.timestamp;
"""
df = pd.read_sql(query, conn)


print(df["id_employee"].unique())

['EMP-0025' 'EMP-0028' 'EMP-0053']

In [15]:
query = """
SELECT 
    c.id_employee, 
    c.timestamp, 
    e.app_name, 
    e.window_title, 
    e.event, 
    e.url, 
    c.image_path
FROM captures c
JOIN events e ON c.event_id = e.id
ORDER BY c.id_employee, c.timestamp;
"""

df = pd.read_sql(query, conn)

df["timestamp"] = pd.to_datetime(df["timestamp"], format='ISO8601')

stats = df.groupby("id_employee")["timestamp"].agg(['min', 'max'])
print(stats)

                                         min                              max
id_employee
EMP-0025    2026-02-23 06:27:13.258000+00:00 2026-02-26 04:57:55.073128+00:00
EMP-0028    2026-02-23 10:09:51.782000+00:00 2026-02-25 14:24:20.203470+00:00
EMP-0053    2026-02-23 07:41:41.343000+00:00 2026-02-25 14:56:37.027637+00:00

In [16]:
df["image_path"].head()

0    https://fra1.digitaloceanspaces.com/mgscreensh...
1    https://fra1.digitaloceanspaces.com/mgscreensh...
2    https://fra1.digitaloceanspaces.com/mgscreensh...
3    https://fra1.digitaloceanspaces.com/mgscreensh...
4    https://fra1.digitaloceanspaces.com/mgscreensh...
Name: image_path, dtype: object

In [20]:
df.sort_values("timestamp")[[
    "timestamp",
    "app_name",
    "event",
    "url"
]].head(20)

,timestamp,app_name,event,url
0,2026-02-23 06:27:13.258000+00:00,Taskmgr.exe,APP_SWITCH,
1,2026-02-23 06:30:22.306000+00:00,flet.exe,APP_SWITCH,
2,2026-02-23 06:33:23.274000+00:00,unknown,APP_SWITCH,
3,2026-02-23 06:34:05.008000+00:00,brave.exe,TYPE,calendar.google.com/calendar/u/0/r/month
4,2026-02-23 06:49:50.933000+00:00,LockApp.exe,APP_SWITCH,
5,2026-02-23 06:49:53.405000+00:00,flet.exe,APP_SWITCH,
6,2026-02-23 06:49:58.251279+00:00,brave.exe,Custom_CLICK,calendar.google.com/calendar/u/0/r/month
7,2026-02-23 06:50:00.002000+00:00,Postman.exe,CLICK,
8,2026-02-23 06:50:02.870000+00:00,brave.exe,APP_SWITCH,
9,2026-02-23 06:50:05.007000+00:00,Postman.exe,CLICK,
10,2026-02-23 06:50:05.172679+00:00,brave.exe,Custom_CLICK,
11,2026-02-23 06:50:05.956000+00:00,explorer.exe,APP_SWITCH,
12,2026-02-23 06:50:08.003000+00:00,Postman.exe,APP_SWITCH,
13,2026-02-23 06:50:14.168267+00:00,Postman.exe,Custom_CLICK,
14,2026-02-23 06:50:23.429000+00:00,Postman.exe,APP_SWITCH,
15,2026-02-23 06:50:24.456000+00:00,Postman.exe,APP_SWITCH,
16,2026-02-23 06:50:47.603056+00:00,brave.exe,Custom_CLICK,app.afromessage.com/messages
17,2026-02-23 06:50:53.124722+00:00,brave.exe,Custom_CLICK,app.afromessage.com/login
18,2026-02-23 06:50:54.876378+00:00,brave.exe,Custom_CLICK,
19,2026-02-23 06:50:55.010000+00:00,brave.exe,CLICK,youtube.com/?feature=ytca